before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: GAoFQ6pPczWJiQY2/l9MU29uefuo4cvaU2qyMzMsVawtXWldkTKxn588Z+u0dvjBZNT+dYE2hHWW/c+XGpa+3phZDpJad2NZk8d+AbiRLlnl9oaK3xFC0aboISZY6JFc1txUzqbos757svRMPDBVT+oqMIjH9zAI30RKwm6dhxJPKp2tcC+8xWQ9wpKqQTzojn9IYZtIapCCF4Nlj/+Uu7jNqc1odRFAaEg7qIii2nJK8NV0rwnJ+iJpyuT/I/KnORLs6jXwOdtcBZysiQzC1WzO2U2DeOI3S0VcGNDyOnLcL8nTG+Xf6EzVmEUxM4WjyqFRKpit53AhBV5Koe74YMeKGjfckZVQV6IkkGjyXbNmMDqYdTik2DxHHTDzCoInitham1LOFcyEWnm8X+vmqLvzxOcHt2TQ9WgNqXRdw6XNjfwpXaYWLOtJGSNbqBcGocYyc8wTuoyk3kCaKktSiYSjPxUhr6m+lWiWtL4C84ayDylsLhTX1Dtg73lFJDuUCNTqJjGATWzQRNkcUgerojkHSdNgGHkTPJY+OO8tjgw8CXSa6M2AD/E0YDsPGXthZVFVo1+aOqRr0sZkzZmOT0cygmzHCf7/E3C24rY8nwra8SO5lG43DDRkYF3gHcK6Nq7tgLjxGpgc2RO/7pLmUCeGKnt9wXyGADqFzs6Y3Is= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
